name: Example
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Generate ZIP
        uses: byteever/action-build-zip@master
        with:
          filename: template.zip
      - name: list files
        run: |
          ls -ltrR
  
      - name: aws-credentials
        # You may pin to the exact commit or the version.
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          # AWS Region, e.g. us-east-2
          aws-region: eu-west-2
          # The Amazon Resource Name (ARN) of the role to assume. Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials.
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-session-name: github-action-main
      - name: Upload to S3
        run: |
          aws s3 sync build/codemetrics-deploy.zip s3://${{ secrets.DEPLOYMENT_BUCKET }}/codemetrics-deploy.zip
    
